### PR TITLE
Update documentation to include required go packages

### PR DESCRIPTION
**Pull request by smford**
Explicitily define which go packages are needed.

### CODE REVIEW

**Comment by Panda911** [comment]
this isn't actually all of the required packages. i may look at adding them to the actual code generation.
here is a more complete list though im not sure if it ends up using more then this depending on flags

import "net/http"
import "encoding/json"
import "bytes"

**Comment by mholt** [comment]
I think most Go editors handle this automatically with `goimports`...

**Comment by Panda911** [comment]
there's a tool that can do this is not a good excuse its kinda standard in all the other converters. like this one https://curl.trillworks.com that also supports go.

**Comment by mholt** [comment]
@Panda911 Sure it is, because I say it's out of scope for this project. That site writes a whole program for you, this tool does not. You'll just have to respect that. I'm not interested in generating whole programs.

Also it's not "kinda standard" -- there is no standard for tools that generate code from curl commands.

**Comment by Panda911** [comment]
@mholt  i wouldn't say it writes the whole program but it gives you code that will actually compile and if you already have the dependences in your program you can just not paste them.
your right i meant actually standard its what all the other ones do thus it is standard among curl to Lang converters. you may want to rename your project. 
have a great day :)

**Comment by mholt** [comment]
@Panda911 No thanks, but you're welcome to fork it if you want it so badly. It's open source, after all.

But if it's too much work, I totally understand. :wink:

**Pull request closed without merging**
