### PR TITLE
Handle multi-line curl command

### LINKED ISSUE #36: Bug: newlines not working
Hi,

Your latest update has a bug where new lines (using \) are not working. Even some of your examples don't work anymore.

### PR DESCRIPTION
**Pull request by doggy8088**
Fixes #36

### CODE REVIEW

**Comment by doggy8088** [comment]
@mholt Can you take a look on my PR? Thanks

**Comment by mholt** [comment]
What is the problem exactly?

**Comment by doggy8088** [comment]
@mholt There are some curl commands like this, which is multi-line command. Your current version can't handle multiline well. I fixed it.

```sh
curl -X POST https://api.easypost.com/v2/shipments \
     -u API_KEY: \
     -d 'shipment[to_address][id]=adr_HrBKVA85' \
     -d 'shipment[from_address][id]=adr_VtuTOj7o' \
     -d 'shipment[parcel][id]=prcl_WDv2VzHp' \
     -d 'shipment[is_return]=true' \
     -d 'shipment[customs_info][id]=cstinfo_bl5sE20Y'
```

**Comment by bakert** [comment]
I had a dig into what was going on here and added my notes to #36.

**Comment by mholt** [comment]
Is this fixed in #41 then @bakert ?

**Comment by bakert** [comment]
> Is this fixed in #41 then @bakert ?

Yes!

**Comment by mholt** [comment]
Great, thanks so much

**Comment by doggy8088** [comment]
@mholt Would you please push the latest version to https://mholt.github.io/curl-to-go/ ?

**Comment by mholt** [comment]
It should deploy automatically, this is the gh-pages branch.

**Comment by doggy8088** [comment]
Fixed by https://github.com/mholt/curl-to-go/pull/41

**Pull request closed without merging**
